### PR TITLE
chore(ci): macos-latest + windows-latest

### PR DESCRIPTION
**Pull request by Tieske**
testing ci additions

### CODE REVIEW

**Comment by hishamhm** [comment]
@Tieske no idea what's causing this error, unfortunately, but I've added a mitigation to the crash that should hopefully provide more diagnostics if it happens again: https://github.com/luarocks/luarocks/commit/8d0df029b0da53d049f3b02e5e83b21c6000a583

It's probably about time I push a new LuaRocks release, too...

**Comment by hishamhm** [comment]
The Windows dependency actually built this time, but the Windows bindir wasn't added to the PATH... :thinking:

**Comment by Tieske** [comment]
which component is responsible for adding the BinDir? I saw the luarocks action does set the path, but somehow doesn't work.

The error is a PowerShell one, so seems the commands are executed in PowerShell. Does the action update the correct paths?

**Comment by Tieske** [comment]
this looks correct; https://github.com/hishamhm/gh-actions-luarocks/blob/master/main.js#L121

**Comment by hishamhm** [comment]
> this looks correct; https://github.com/hishamhm/gh-actions-luarocks/blob/master/main.js#L121

Yeah, this was supposed to be the one to do it. I have no idea why this didn't work

**Comment by hishamhm** [comment]
Can you work around it by explicitly setting the PATH in your CI script? It would be interesting to know if that at least works...

**Comment by Tieske** [comment]
So I added some debugging, but it (the busted executable) seems to be gone....

Here's the log: https://github.com/lunarmodules/luasystem/actions/runs/8161889298/job/22311635078?pr=17#step:6:13

Here's an edited version with commands and results:
> `luarocks config deploy_bin_dir`
```
C:\Users\runneradmin\AppData\Roaming\luarocks\bin
```

> `$env:PATH`
```
C:\Program Files\PowerShell\7;
C:\Users\runneradmin\AppData\Roaming\luarocks\bin;
D:\a\luasystem\luasystem\.luarocks\bin;
D:/a/luasystem/luasystem/.lua/bin;
C:\Program Files\MongoDB\Server\5.0\bin;
C:\aliyun-cli;
C:\vcpkg;
C:\Program Files (x86)\NSIS\;
C:\tools\zstd;
C:\Program Files\Mercurial\;
C:\hostedtoolcache\windows\stack\2.15.1\x64;
C:\cabal\bin;
C:\\ghcup\bin;
C:\mingw64\bin;
C:\Program Files\dotnet;
C:\Program Files\MySQL\MySQL Server 8.0\bin;
C:\Program Files\R\R-4.3.2\bin\x64;
C:\SeleniumWebDrivers\GeckoDriver;
C:\SeleniumWebDrivers\EdgeDriver\;
C:\SeleniumWebDrivers\ChromeDriver;
C:\Program Files (x86)\sbt\bin;
C:\Program Files (x86)\GitHub CLI;
C:\Program Files\Git\bin;
C:\Program Files (x86)\pipx_bin;
C:\npm\prefix;
C:\hostedtoolcache\windows\go\1.21.7\x64\bin;
C:\hostedtoolcache\windows\Python\3.9.13\x64\Scripts;
C:\hostedtoolcache\windows\Python\3.9.13\x64;
C:\hostedtoolcache\windows\Ruby\3.0.6\x64\bin;
C:\Program Files\OpenSSL\bin;
C:\tools\kotlinc\bin;
C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\8.0.402-6\x64\bin;
C:\Program Files\ImageMagick-7.1.1-Q16-HDRI;
C:\Program Files\Microsoft SDKs\Azure\CLI2\wbin;
C:\ProgramData\kind;
C:\ProgramData\Chocolatey\bin;
C:\Windows\system32;
C:\Windows;
C:\Windows\System32\Wbem;
C:\Windows\System32\WindowsPowerShell\v1.0\;
C:\Windows\System32\OpenSSH\;
C:\Program Files\dotnet\;
C:\Program Files\PowerShell\7\;
C:\Program Files\Microsoft\Web Platform Installer\;
C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;
C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;
C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;
C:\Program Files\Microsoft SQL Server\130\DTS\Binn\;
C:\Program Files\Microsoft SQL Server\140\DTS\Binn\;
C:\Program Files\Microsoft SQL Server\150\DTS\Binn\;
C:\Program Files\Microsoft SQL Server\160\DTS\Binn\;
C:\Strawberry\c\bin;
C:\Strawberry\perl\site\bin;
C:\Strawberry\perl\bin;
C:\ProgramData\chocolatey\lib\pulumi\tools\Pulumi\bin;
C:\Program Files\TortoiseSVN\bin;
C:\Program Files\CMake\bin;
C:\ProgramData\chocolatey\lib\maven\apache-maven-3.8.7\bin;
C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code;
C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager;
C:\Program Files\nodejs\;
C:\Program Files\Git\cmd;
C:\Program Files\Git\mingw64\bin;
C:\Program Files\Git\usr\bin;
C:\Program Files\GitHub CLI\;
c:\tools\php;
C:\Program Files (x86)\sbt\bin;
C:\Program Files\Amazon\AWSCLIV2\;
C:\Program Files\Amazon\SessionManagerPlugin\bin\;
C:\Program Files\Amazon\AWSSAMCLI\bin\;
C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;
C:\Program Files\LLVM\bin;
C:\Users\runneradmin\.dotnet\tools;
C:\Users\runneradmin\.cargo\bin;
C:\Users\runneradmin\AppData\Local\Microsoft\WindowsApps
```

> `dir D:\a\luasystem\luasystem\.luarocks\bin`
```
    Directory: D:\a\luasystem\luasystem\.luarocks\bin

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           2/27/2024  3:19 PM        4165805 luarocks-admin.exe
-a---           2/27/2024  3:19 PM        4165784 luarocks.exe
```

> `dir C:\Users\runneradmin\AppData\Roaming\luarocks\bin`
```
Get-ChildItem: D:\a\_temp\8321d916-67e9-4167-864d-9ed40ff651c7.ps1:5
Line |
   5 |  dir C:\Users\runneradmin\AppData\Roaming\luarocks\bin
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'C:\Users\runneradmin\AppData\Roaming\luarocks\bin' because it does not exist.
Error: Process completed with exit code 1.
```

**Comment by Tieske** [comment]
hmmm... this entry `D:/a/luasystem/luasystem/.lua/bin;` is not properly normalized for Windows (slash instead of back-slash). So maybe that's the culprit.

**Comment by Tieske** [comment]
Also not the case;

> `dir D:\a\luasystem\luasystem\.lua\bin`
```
     Directory: D:\a\luasystem\luasystem\.lua\bin
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
la---           2/29/2024  9:24 AM              0 lua.exe -> luajit-2.1.0-beta3.exe
-a---           2/29/2024  9:24 AM         480666 lua51.dll
-a---           2/29/2024  9:24 AM          29875 luajit-2.1.0-beta3.exe
```

**Comment by hishamhm** [comment]
@Tieske Looks like all is running green, including Windows, with the upcoming LuaRocks 3.11 for Workgroups! (How appropriate :) )

Since Windows builds transitioned to Actions, I've added a commit here to remove appveyor.yml and removed the Webhook, I don't know if anything else needs to be done on your Appveyor account as well.

**Comment by Tieske** [comment]
Looking good so far. What I noticed is that it uses the gcc toolchain. afaik the only one included would be the MSYS one.

I didn't see anything on the action to specify what toolchain to use, is there an option to use the WinSDK, or VS studio toolchains?
Ideally I'd like to run multiple jobs against different toolchains.

**Comment by hishamhm** [comment]
> I didn't see anything on the action to specify what toolchain to use, is there an option to use the WinSDK, or VS studio toolchains?

I thiiiink if you run this from an environment where %VCINSTALLDIR% is set (that, if the MSVC activation stuff was executed) then it miiiight just work?... worth a try!

**Comment by Tieske** [comment]
> > I didn't see anything on the action to specify what toolchain to use, is there an option to use the WinSDK, or VS studio toolchains?
> 
> I thiiiink if you run this from an environment where %VCINSTALLDIR% is set (that, if the MSVC activation stuff was executed) then it miiiight just work?... worth a try!

so you're saying the action doesn't do anything special? It's LuaRocks own detection mechanism that find the toolchain?

**Comment by hishamhm** [comment]
yes, that's the idea. To use MSVC you need to and an extra action to the
job, see the gh-actions-lua readme!

**Comment by hishamhm** [comment]
@Tieske  just added a job running with the Microsoft toolchain!

**Comment by hishamhm** [comment]
I triggered a MSVC job for testing above, and it succeeded building Lua, LuaRocks and the dependencies, but when trying to load the luafilesystem module it failed — that seems to indicate that LuaRocks's autodetection of MSVC _almost_ worked. By looking at the cl.exe and link.exe calls in the log, do you have an idea of what's wrong?

**Comment by Tieske** [comment]
```
relevant part from the logs:
============================

penlight 1.13.1-1 depends on luafilesystem (not installed)
Installing https://luarocks.org/luafilesystem-1.8.0-1.src.rock

luafilesystem 1.8.0-1 depends on lua >= 5.1 (5.4-1 provided by VM: success)
cl /nologo /MD /O2 -c -Fosrc/lfs.obj -ID:/a/luasystem/luasystem/.lua/include src/lfs.c
link -dll -def:lfs.def -out:C:\Users\RUNNER~1\AppData\Local\Temp\luarocks_build-LuaFileSystem-1.8.0-1-8719918\lfs.dll D:\a\luasystem\luasystem\.lua\lib\lua54.lib src/lfs.obj
luafilesystem 1.8.0-1 is now installed in C:\Users\runneradmin\AppData\Roaming\luarocks (license: MIT/X11)

Here's a local build MSVC (VS 2022 command prompt)
==================================================
todo
```

**Comment by Tieske** [comment]
what's this weird error message? 
`D:/a/luasystem/luasystem/.lua/bin\lua.exe: error loading module 'lfs' from file 'C:\Users\runneradmin\AppData\Roaming\luarocks\lib\lua\5.4\lfs.dll':
	The specified module could not be found.
`

**Comment by Tieske** [comment]
managed to add Dependencies utility to check the exports, but they seem fine:
```
{
  "Exports": [
    {
      "Ordinal": 1,
      "Name": "luaopen_lfs",
      "ExportByOrdinal": false,
      "VirtualAddress": 8880,
      "ForwardedName": ""
    }
  ]
}
```
I thought maybe the weird error was because it couldn't find the function to open the lib.

**Comment by hishamhm** [comment]
> what's this weird error message?
> D:/a/luasystem/luasystem/.lua/bin\lua.exe: error loading module 'lfs' from file 'C:\Users\runneradmin\AppData\Roaming\luarocks\lib\lua\5.4\lfs.dll': The specified module could not be found. 

Yeah, that's the mystery...

Thanks for making the local build for  comparing with the logs... the cl.exe and link.exe command line look effectively identical, as far as I can tell.

**Comment by hishamhm** [comment]
Oh, looks like this may be the cause: https://github.com/leafo/gh-actions-lua/pull/38/files

**Comment by hishamhm** [comment]
@Tieske ...and we got a green build at last!!

I pulled these four PRs into my fork of gh-actions-lua:
* https://github.com/leafo/gh-actions-lua/pull/35
* https://github.com/leafo/gh-actions-lua/pull/37
* https://github.com/leafo/gh-actions-lua/pull/38
* https://github.com/leafo/gh-actions-lua/pull/41

(I didn't pull https://github.com/leafo/gh-actions-lua/pull/44 because that seems like a deeper change, which may also need fixing conflicts with the other ones, and I'm not sure if that would work out of the box anyway — I didn't test it, just wanted the issue we have at hand here to get over with.)

I had to delete the cache for the Lua 5.4 windows build manually. And it looks like the cache key in gh-actions-lua doesn't check for gcc vs msvc. It probably needs a super-specific cache key with all of the msvc variants stuff... LuaRocks is also bad at this regard, we just call everything "win32" and only differ on CPU arch... so heads up on that.

Another thing to note is that I think the combo luajit+msvc isn't supported by these actions yet, because we're using the Makefile to build luajit. (And so does https://github.com/leafo/gh-actions-lua/pull/44, so that PR wouldn't help on this front either).

But I think we're in a pretty good shape to get this PR cleaned up and your luasystem CI set up. And I think I'm looking good for releasing LuaRocks 3.11 as well!

**Comment by Tieske** [comment]
ha, finally! thx for the hard work @hishamhm 🙏 

So where to go from here; clean up and merge using the forks, or wait for @leafo to merge them upstream? (or maybe even move the upstream projects into LunarModules and set up a larger support team if @leafo is ok with that?)

**Comment by hishamhm** [comment]
I'd say just clean up and merge using the forks as-is for the time being. If anything else happens with the actions, you can always get back here and have them point elsewhere.

**Comment by hishamhm** [comment]
@Tieske do you have anything else you need to change here? I think even keeping the Dependencies Analyzer stuff around should be fine (I've gated it for the msvc run only). So I'd say how about we take this PR, squash it into a single commit and merge? You can always add more CI jobs later if you feel like it.

**Comment by Tieske** [comment]
over the weekend I tried adding also a MinGW job, but that failed. Ideally we'd have jobs for msvc and MinGW. Haven't looked into the cache key issue you mentioned before yet, maybe that's the culprit.

Also; wondering if we should keep this as 1 workflow, or have separate ones for posix-like and Windows.

**Comment by hishamhm** [comment]
The existing one for "windows-latest, luajit" is mingw already, isn't it? it's not MSVC, and uses gcc on Windows.

**Comment by Tieske** [comment]
ok, tried that, but now it keeps looking for the msvc toolchain; https://github.com/lunarmodules/luasystem/actions/runs/8297960620/job/22710219967?pr=17

Added a mingw build for a different Lua version. In the logs you can see that the 2 msvc specific steps are skipped (as they should). But it still looks for the `cl` command;

```
Error: Failed to install Lua: Error: Unable to locate executable file: cl. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file.
```

**Comment by Tieske** [comment]
ok, so turns out msvc is required to build Puc Rio Lua versions by the action, So no MinGW for those versions.

So the LuaJIT builds will test the MinGW toolchain, since they are build using that one. And the PuC Rio ones will use MSVC. I think that should suffice.

**Pull request merged**
